name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'
  access_submodules_token:
    description: Access submodules and private github packages
    required: true

runs:
  using: composite
  steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.access_submodules_token }}
        submodules: true
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: setup pnpm
      uses: @jfabraxas/github-actions/.github/actions/pnpm/setup
    # issue:
    # - https://github.com/pnpm/pnpm/issues/2933
    # - https://stackoverflow.com/questions/69932834/is-there-some-problem-using-pnpm-with-github-packages
    - name: Install dependencies
      shell: bash
      run: |
        npm config set //npm.pkg.github.com/:_authToken $TOKEN
        pnpm install
      env:
        TOKEN: ${{ inputs.access_submodules_token }}
