name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'
  access_submodules_token:
    description: Access submodules and private github packages
    required: true

outputs:
  base:
    description: BASE Sha
    value: ${{ steps.setShas.outputs.base }}
  head:
    description: HEAD Sha
    value: ${{ steps.setShas.outputs.head }}

runs:
  using: composite
  steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.access_submodules_token }}
        submodules: true
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      id: setShas
      uses: nrwl/nx-set-shas@v2
    - shell: bash
      run: |
          echo "BASE: ${{ steps.setShas.outputs.base }}"
          echo "HEAD: ${{ steps.setShas.outputs.head }}"
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: setup pnpm
      uses: jfabraxas/github-actions/.github/actions/pnpm/setup@main
    # issue:
    # - https://github.com/pnpm/pnpm/issues/2933
    # - https://stackoverflow.com/questions/69932834/is-there-some-problem-using-pnpm-with-github-packages
    - name: Install dependencies
      shell: bash
      run: |
        npm config set //npm.pkg.github.com/:_authToken $TOKEN
        pnpm install --no-optional
      env:
        TOKEN: ${{ inputs.access_submodules_token }}
    - shell: bash
      run: |
        echo "finished SETUP with BASE: ${{ steps.setShas.outputs.base }} and HEAD: ${{ steps.setShas.outputs.head }}"
