name: 'Nx migrate'
desctiption: https://github.com/jscutlery/semver/blob/main/.github/workflows/nx-migrate.yml

inputs:
  github_token:
    requried: true
  migrate_token:
    required: true

runs:
  using: composite
  steps:
    - name: Check if @nrwl/workspace is outdated
      id: nrwl-workspace-outdated
      shell: bash
      run: |
        IS_OUTDATED=$(test ! -z "$(pnpm outdated @nrwl/workspace)" && echo true || echo false)
        echo $IS_OUTDATED
        echo "::set-output name=outdated::$IS_OUTDATED"
    - name: Check if has migrations
      id: nrwl-workspace-has-migrations
      shell: bash
      run: |
        HAS_MIGRATIONS=$(test -f migrations.json && echo true || echo false)
        echo $HAS_MIGRATIONS
        echo "::set-output name=has_migrations::$HAS_MIGRATIONS"
    - name: Update @nrwl/workspace
      if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
      shell: bash
      run: pnpm nx migrate next

    - name: Install dependencies
      if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
      shell: bash
      run: pnpm install --no-frozen-lockfile

    - name: Run @nrwl/workspace migrations
      if: steps.nrwl-workspace-has-migrations.outputs.has_migrations == 'true'
      shell: bash
      run: pnpm nx migrate --run-migrations

    # - name: Test
    #   id: test
    #   if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
    #   continue-on-error: true
    #   uses: ./.github/actions/test
    #   with:
    #     codecov_token: ${{ secrets.CODECOV_TOKEN }}

    - name: Commit changes
      if: steps.nrwl-workspace-outdated.outputs.outdated == 'true'
      shell: bash
      run: |
        git add .
        [[ $(git status --porcelain) ]] && git commit -m "build: 📦 update nrwl workspace" || echo "nothing to commit"
    - name: Remove migrations.json & commit
      if: steps.nrwl-workspace-has-migrations.outputs.has_migrations == 'true'
      shell: bash
      run: |
        git rm -f migrations.json
        git commit -m "build: 📦 remove migrations.json"
    - name: Push changes
      if: steps.nrwl-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true

    - name: Create PR
      if: steps.nrwl-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome != 'success'
      shell: bash
      run: |
        LAST_VERSION=$(npm view @nrwl/workspace version)
        BRANCH="update-nrwl-workspace-${LAST_VERSION}"
        git checkout -b "${BRANCH}"
        git push -f --set-upstream origin "${BRANCH}"
        PR=$(gh pr view "${BRANCH}")
        if [[ $PR == *"no pull requests found"* ]]; then
          gh pr create -t "Update @nrwl/workspace" -b "Update @nrwl/workspace dependencies to ${LAST_VERSION}."
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.migrate_token }}
