name: PNPM Setup

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4.1.0 # v2.2.2
      id: pnpm-install
      with:
        version: latest
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: |
          ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          **/node_modules
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
