name: forklike sync

description: syncing like a fork

inputs:
   git_user_email:
    description: Node.js version
    required: true
  git_user_name:
    description: Access submodules and private github packages
    required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Alle Commits holen

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Add Public Repository as upstream
        run: |
          git remote add upstream https://github.com/QuivrHQ/quivr
          git fetch upstream

      - name: Sync with upstream
        run: |
          # Stelle sicher, dass wir auf dem main Branch arbeiten
          git checkout main

          # Mache einen rebase, um die Änderungen des upstream-Repos zu integrieren
          git rebase upstream/main

      - name: Handle Rebase Conflicts
        if: failure()  # Dieser Schritt wird nur ausgeführt, wenn der vorherige fehlgeschlagen ist
        run: |
          echo "Rebase failed due to conflicts. Please resolve them manually."
          exit 1

      - name: Push changes to Private Repository
        run: |
          # Wenn alles erfolgreich ist, pushe die Änderungen in das private Repo
          git push origin main --force-with-lease
